version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - oracle
    ports:
      - "8080:8080"

  oracle:
    image: gvenzl/oracle-free:23-slim
    container_name: oracle
    environment:
      - ORACLE_PASSWORD=oracle
      - APP_USER=oracle
      - APP_USER_PASSWORD=oracle
    ports:
      - "1521:1521"
      - "5500:5500"
