spring:
  datasource:
    url: jdbc:oracle:thin:@oracle:1521/FREEPDB1
    username: oracle
    password: oracle
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

logging:
  level:
    root: INFO
    com.proyectos.comprobantespago: DEBUG
    org.hibernate.SQL: DEBUG
